applicationId: "MyApplication"

server:
  applicationConnectors:
    - type: http
      port: 2104
  adminConnectors:
    - type: http
      port: 2105

commandAggregatorAddress: http://localhost:2104
outputAggregatorAddress: http://localhost:2104

autoPullingCommands: false
autoPullingIntervalSeconds: 1

moduleConfigs:
  - moduleId: first
    qaModule: qa.QAELM

# Logging settings.
logging:
  level: INFO
  appenders:
    - type: console
      target: stderr
    - type: file
      currentLogFilename: ./logs/QALog.log
      archivedLogFilenamePattern: ./logs/QALog-%d.log.gz
      archivedFileCount: 5
  # Logger-specific levels.
  loggers:
    "qa.App":
      level: DEBUG
